[package]
name = "http-request-target"
version = "0.1.0"
description = "HTTP request-target (RFC 9112) parser"
authors = ["Rob Ede <robjtede@icloud.com>"]
categories = ["parsing"]
keywords = ["http", "request", "target", "uri"]
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = ["simd"]
std = ["winnow/std"]
simd = ["winnow/simd"]

[dependencies]
winnow = { version = "1", default-features = false, features = ["binary"] }

[dev-dependencies]
divan = { package = "codspeed-divan-compat", version = "4" }
http = "0.2.9"

[[bench]]
name = "parse-request-target"
harness = false

[lints]
workspace = true
