[package]
name = "http-request-target"
version = "0.1.0"
description = "HTTP request-target (RFC 9112) parser"
authors = ["Rob Ede <robjtede@icloud.com>"]
categories = ["parsing"]
keywords = ["http", "request", "target", "uri"]
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = ["std", "simd"]
std = ["winnow/std", "winnow-rfc3986/std"]
simd = ["winnow/simd", "winnow-rfc3986/simd"]

[dependencies]
impl-more = "0.3"
winnow = { version = "1", default-features = false, features = ["ascii", "binary"] }
winnow-rfc3986 = { path = "../winnow-rfc3986", version = "0.0.2", default-features = false }

[dev-dependencies]
divan = { package = "codspeed-divan-compat", version = "4" }
http = "1"

[[bench]]
name = "parse-request-target"
harness = false

[lints]
workspace = true
