[package]
name = "http-core"
version = "0.0.1"
description = "Primitive HTTP types"
authors = ["Rob Ede <robjtede@icloud.com>"]
categories = ["network-programming", "parsing"]
keywords = ["http", "core", "types"]
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[package.metadata.cargo_check_external_types]
allowed_external_types = [
  "http_field::*",
  "http_method::*",
  "http_request_target::*",
  "http_status_code::*",
  "http_version::*",
  "winnow_rfc3986::*",
  "winnow_rfc9110::*",
  "winnow_rfc9112::*",
]

[dependencies]
http-chunked = { path = "../http-chunked", version = "0.0.1" }
http-field = { path = "../http-field", version = "0.0.3" }
http-method = { path = "../http-method", version = "0.0.2" }
http-request-target = { path = "../http-request-target", version = "0.1.0" }
http-status-code = { path = "../http-status-code", version = "0.0.2" }
http-version = { path = "../http-version", version = "0.0.2" }
winnow-rfc3986 = { path = "../winnow-rfc3986", version = "0.0.2", default-features = false }
winnow-rfc9110 = { path = "../winnow-rfc9110", version = "0.0.1", default-features = false }

[lints]
workspace = true
