[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
repository = "https://github.com/robjtede/httpea"
license = "MIT"
edition = "2024"
rust-version = "1.92"

[workspace.lints.rust]
rust_2018_idioms = { level = "deny", priority = -1 }
nonstandard_style = { level = "deny", priority = -1 }
future_incompatible = { level = "deny", priority = -1 }
missing_debug_implementations = "warn"
missing_docs = "warn"

[workspace.lints.clippy]
undocumented_unsafe_blocks = "deny"
