[package]
name = "winnow-rfc9112"
version = "0.0.1"
description = "Winnow parsers for RFC 9112 HTTP/1.1 syntax productions"
authors = ["Rob Ede <robjtede@icloud.com>"]
categories = ["parsing"]
keywords = ["winnow", "http", "rfc9112"]
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[package.metadata.cargo_check_external_types]
allowed_external_types = ["winnow::*"]

[features]
default = ["std", "simd"]
std = ["winnow/std", "winnow-rfc9110/std"]
simd = ["winnow/simd", "winnow-rfc9110/simd"]

[dependencies]
winnow = { version = "1", default-features = false, features = ["binary"] }
winnow-rfc9110 = { path = "../winnow-rfc9110", version = "0.0.1", default-features = false }

[lints]
workspace = true
