[package]
name = "winnow-rfc3986"
version = "0.0.1"
description = "Winnow parsers for RFC 3986 URI syntax productions"
authors = ["Rob Ede <robjtede@icloud.com>"]
categories = ["parsing"]
keywords = ["winnow", "uri", "rfc3986"]
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = ["std", "simd"]
std = ["winnow/std"]
simd = ["winnow/simd"]

[dependencies]
winnow = { version = "1", default-features = false, features = ["ascii", "binary"] }

[dev-dependencies]
divan = { package = "codspeed-divan-compat", version = "4" }

[[bench]]
name = "rfc3986"
harness = false

[lints]
workspace = true
