[package]
name = "qpack"
version = "0.0.1"
publish = false
authors = ["Rob Ede <robjtede@icloud.com>"]
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
byteorder = "1.4.3"
impl-more = "0.1.5"

[[bench]]
name = "var-int"
harness = false

[dev-dependencies]
criterion = { version = "4", package = "codspeed-criterion-compat", features = ["html_reports"] }
