[package]
name = "http-field"
version = "0.0.3"
description = "HTTP fields (headers & trailers)"
authors = ["Rob Ede <robjtede@icloud.com>"]
categories = ["parsing"]
keywords = ["http", "field", "fields", "header", "trailer"]
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[package.metadata.cargo-shear]
ignored = [
  "quickcheck", # used by quickcheck_macros
]

[features]
default = ["std", "simd"]
std = ["winnow/std", "winnow-rfc9110/std"]
simd = ["winnow/simd", "winnow-rfc9110/simd"]

[dependencies]
winnow = { version = "1", default-features = false, features = ["binary"] }
winnow-rfc9110 = { path = "../winnow-rfc9110", version = "0.0.1", default-features = false }

[dev-dependencies]
divan = { package = "codspeed-divan-compat", version = "4" }
quickcheck = { version = "1", default-features = false }
quickcheck_macros = "1"

[[bench]]
name = "http-field"
harness = false

[lints]
workspace = true
